name: awesome_drawer_bar
description: A Flutter package with custom implementation of the Side Menu (Drawer)
version: 1.0.0
homepage: https://appcheap.io
repository: https://github.com/AppCheap/awesome_drawer_bar

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
